name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@81d310742121c928ea9c8bbd407b4217b432ae02  # v2.0.0

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Install required board core
        run: arduino-cli core install arduino:avr@1.8.7  # např. pro Arduino Uno
      
      - name: Install libraries
        run: |
          arduino-cli lib install "Ds1302@1.1.0"
          arduino-cli lib install "LiquidCrystal_I2C@2.0.0"
          arduino-cli lib install "DallasTemperature@4.0.6"
          arduino-cli lib install "OneWire@2.3.8"
          arduino-cli lib install "MQTTESP8266@5.1.2"
          arduino-cli lib install "TX07K-TXC@1.0.4"

      - name: Set configs
        run: |
          cp config_default.h config.h
          cp sensorsconfig_default.h sensorsconfig.h

      - name: Static analysis
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --language=c++ --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=unusedStructMember --suppress=noExplicitConstructor --suppress=noCopyConstructor --suppress=noOperatorEq --suppress=cstyleCast --suppress=constParameterCallback --suppress=constParameterPointer --suppress=constVariablePointer --suppress=unsignedLessThanZero --suppress=unsignedPositive --suppress=checkersReport --error-exitcode=1 *.ino *.cpp *.h

      - name: Compile Arduino project
        run: |
          arduino-cli compile --fqbn arduino:avr:mega ./
